$.ku.localization = {
    en:{
        day:{
            name:{
                0:"Sunday",
                1:"Monday",
                2:"Tuesday",
                3:"Wednesday",
                4:"Thursday",
                5:"Friday",
                6:"Saturday"
            },
            abbr:{
                0:"Sun",
                1:"Mon",
                2:"Tue",
                3:"Wed",
                4:"Thu",
                5:"Fri",
                6:"Sat"
            }
        },
        month:{
            name:{
                1:"January",
                2:"February",
                3:"March",
                4:"April",
                5:"May",
                6:"June",
                7:"July",
                8:"August",
                9:"September",
                10:"October",
                11:"November",
                12:"December"
            },
            abbr:{
                1:"Jan",
                2:"Feb",
                3:"Mar",
                4:"Apr",
                5:"May",
                6:"Jun",
                7:"Jul",
                8:"Aug",
                9:"Sep",
                10:"Oct",
                11:"Nov",
                12:"Dec"
            }
        }
    },
    sp:{
        day:{
            name:{
                0:"domingo",
                1:"lunes",
                2:"martes",
                3:"mi&#0233;rcoles",
                4:"jueves",
                5:"viernes",
                6:"sábado"
            },
            abbr:{
                0:"dom",
                1:"lun",
                2:"mar",
                3:"mi&#0233;",
                4:"jue",
                5:"vie",
                6:"s&#0225;b"
            }
        },
        month:{
            name:{
                1:"enero",
                2:"febrero",
                3:"marzo",
                4:"abril",
                5:"mayo",
                6:"junio",
                7:"julio",
                8:"agosto",
                9:"septiembre",
                10:"octubre",
                11:"noviembre",
                12:"diciembre"
            },
            abbr:{
                1:"ene",
                2:"feb",
                3:"mar",
                4:"abr",
                5:"may",
                6:"jun",
                7:"jul",
                8:"ago",
                9:"sep",
                10:"oct",
                11:"nov",
                12:"dic"
            }
        }
    }
}